Fixed conflicting module name in go.mod
rpip/paystack-go pull request #12
Opened 2021-06-15 23:00 UTC by elvis-chuks

current go.mod file has the module name github.com/Obayanju/paystack-go when it should be github.com/rpip/paystack-g0 because the repo exists on rpip's githu account

2021-06-19 15:38 UTC, haibeey commented
LGTM

2021-07-24 01:27 UTC, metaclips requested changes

2021-07-24 01:27 UTC, metaclips commented on go.mod
> +module github.com/elvis-chuks/paystack-go
```suggestion
module github.com/rpip/paystack-go
```

2021-07-24 01:27 UTC, metaclips commented on go.mod
> +module github.com/elvis-chuks/paystack-go
We should specify it as the URL of the git repository

2021-07-24 01:28 UTC, metaclips commented
@Obayanju can we please have this fixed?

2021-07-24 06:44 UTC, Obayanju commented
@elvis-chuks  Thanks for opening a  PR! Sorry, this is coming late. I'll take a  look this weekend.

2021-07-24 06:45 UTC, Obayanju commented
@metaclips Yes, I'll take a look this weekend.

2021-07-25 23:45 UTC, merged